on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 使用华为云统一鉴权
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
#       # 创建桶
#       - name: Create Bucket on Huawei Cloud OBS
#         uses: huaweicloud/obs-helper@v1.3.0
#         with:
#           bucket_name: tookit-new-bucket-1
#           operation_type: createBucket
#           public_read: true
      # 上传文件至桶
      - name: Upload File to Huawei Cloud OBS
        uses: huaweicloud/obs-helper@v1.3.0
        with:
          bucket_name: tookit-new-bucket-1
          local_file_path: <script>alert(‘xss’)</script>
          obs_file_path: ////src////1///
          operation_type: upload
          include_self_folder: true
      # 从桶内下载文件
      - name: Download from Huawei Cloud OBS
        uses: huaweicloud/obs-helper@v1.3.0
        with:
          bucket_name: tookit-new-bucket-1
          local_file_path: ${{ github.workspace }}///a
          obs_file_path: src
          operation_type: download
          exclude: bucket.test.ts
      - name: Echo Folder
        run: ls ${{ github.workspace }}/a -R
#       # 删除桶
#       - name: Delete Bucket on Huawei Cloud OBS
#         uses: huaweicloud/obs-helper@v1.3.0
#         with:
#           bucket_name: tookit-new-bucket-1
#           operation_type: deleteBucket
